from fastapi import FastAPI, Depends, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Optional, Any
import uuid
import requests

from .auth import require_api_key, verify_jwt_token
from .adk_client import call_adk_run
from .config import ADK_BASE_URL, ADK_RUN_URL

app = FastAPI(title="AI Proxy (ADK Secure Gateway)")


# -------------------------------------------------------------------
# MODELS
# -------------------------------------------------------------------

class MessagePart(BaseModel):
    text: str

class NewMessage(BaseModel):
    parts: List[MessagePart]

class StateDelta(BaseModel):
    additionalProp1: Dict[str, Any] = {}

class ChatRequest(BaseModel):
    appName: str
    userId: str
    sessionId: str
    newMessage: NewMessage
    streaming: Optional[bool] = False
    stateDelta: Optional[StateDelta] = StateDelta()


@app.post("/api/session/create")
async def create_session(
    _=Depends(require_api_key),
    user=Depends(verify_jwt_token)
):
    """
    Creates a new ADK session using:
    - userId extracted from JWT
    - autogenerated sessionId
    """

    user_id = user.get("userId")
    if not user_id:
        raise HTTPException(status_code=400, detail="userId missing in JWT payload")

    session_id = str(uuid.uuid4())

    url = f"{ADK_BASE_URL}/api/apps/chat-boat-sql/users/{user_id}/sessions/{session_id}"

    print("➡ Creating ADK session URL:", url)

    try:
        resp = requests.post(url)
        resp.raise_for_status()

        return {
            "message": "Session created successfully",
            "userId": user_id,
            "sessionId": session_id,
            "adkResponse": resp.json()
        }

    except Exception as e:
        print("❌ ERROR calling ADK session:", e)
        raise HTTPException(status_code=500, detail=str(e))



@app.post("/api/chat")
async def chat(
    body: ChatRequest,
    _=Depends(require_api_key),
):
    payload = body.dict()
    response = call_adk_run(payload)
    return response

# test run
@app.get("/health")
async def health():
    return {"status": "ok", "adk_run_url": ADK_RUN_URL}
